"""
AgriCrop Backend - Disease Routes
Endpoints for leaf disease detection, history tracking, and reports.
"""

import os
import uuid
from flask import Blueprint, request, jsonify, current_app
from flask_jwt_extended import jwt_required, get_jwt_identity
from werkzeug.utils import secure_filename
from app.services.disease_service import predict_disease_from_image, get_user_disease_reports, get_disease_report_detail
from app.utils.helpers import format_response

disease_bp = Blueprint("disease", __name__)

ALLOWED_EXTENSIONS = {"png", "jpg", "jpeg", "webp"}


def allowed_file(filename):
    """Check if the uploaded file has a supported image extension."""
    return "." in filename and filename.rsplit(".", 1)[1].lower() in ALLOWED_EXTENSIONS


@disease_bp.route("/predict", methods=["POST"])
@jwt_required()
def predict():
    """
    Accept leaf image upload, run AI disease prediction model,
    save report, and return prediction results.
    """
    try:
        user_id = get_jwt_identity()

        # Check if file is in request files
        if "image" not in request.files:
            res, code = format_response(message="No image file provided in the 'image' field.", status_code=400)
            return jsonify(res), code

        file = request.files["image"]

        if file.filename == "":
            res, code = format_response(message="No selected file.", status_code=400)
            return jsonify(res), code

        if not allowed_file(file.filename):
            res, code = format_response(message="Unsupported file type. Use JPG, PNG or WEBP.", status_code=400)
            return jsonify(res), code

        # Gather extra form parameters
        crop_type = request.form.get("crop_type", "Rice")
        field_id = request.form.get("field_id")
        latitude = request.form.get("latitude")
        longitude = request.form.get("longitude")

        extra_data = {
            "crop_type": crop_type,
            "field_id": field_id
        }

        if latitude and longitude:
            try:
                extra_data["latitude"] = float(latitude)
                extra_data["longitude"] = float(longitude)
            except ValueError:
                pass

        # Save file to upload directory
        filename = secure_filename(file.filename)
        # Create a unique filename to prevent collisions
        file_ext = filename.rsplit(".", 1)[1].lower() if "." in filename else "jpg"
        unique_filename = f"{uuid.uuid4().hex}.{file_ext}"
        
        upload_folder = current_app.config.get("UPLOAD_FOLDER", "uploads")
        if not os.path.exists(upload_folder):
            os.makedirs(upload_folder, exist_ok=True)
            
        file_path = os.path.join(upload_folder, unique_filename)
        file.save(file_path)

        # Run prediction service (it saves report to DB)
        result, err = predict_disease_from_image(user_id, file_path, extra_data)

        if err:
            # Clean up saved file on failure
            if os.path.exists(file_path):
                os.remove(file_path)
            res, code = format_response(message=err, status_code=500)
            return jsonify(res), code

        # Expose file path to frontend (we should serve it statically or return path)
        # For simple setups, returning the relative file path is fine
        result["image_url"] = f"/uploads/{unique_filename}"

        # Update the report record in the DB with the web-accessible URL
        from app import mongo
        from bson import ObjectId
        mongo.db.disease_reports.update_one(
            {"_id": ObjectId(result["report_id"])},
            {"$set": {"image_url": result["image_url"]}}
        )

        res, code = format_response(result, "Disease analysis completed successfully.", 200)
        return jsonify(res), code

    except Exception as e:
        res, code = format_response(message=f"An error occurred during disease prediction: {str(e)}", status_code=500)
        return jsonify(res), code


@disease_bp.route("/reports", methods=["GET"])
@jwt_required()
def reports():
    """Retrieve all disease reports generated by the user."""
    try:
        user_id = get_jwt_identity()
        limit = request.args.get("limit", 20, type=int)

        reports_list, err = get_user_disease_reports(user_id, limit)
        if err:
            res, code = format_response(message=err, status_code=500)
            return jsonify(res), code

        res, code = format_response(reports_list, "Disease reports retrieved successfully.", 200)
        return jsonify(res), code

    except Exception as e:
        res, code = format_response(message=f"An error occurred fetching reports: {str(e)}", status_code=500)
        return jsonify(res), code


@disease_bp.route("/reports/<report_id>", methods=["GET"])
@jwt_required()
def report_detail(report_id):
    """Retrieve details of a specific disease report by ID."""
    try:
        user_id = get_jwt_identity()
        
        report, err = get_disease_report_detail(report_id, user_id)
        if err:
            res, code = format_response(message=err, status_code=404)
            return jsonify(res), code

        res, code = format_response(report, "Disease report details retrieved.", 200)
        return jsonify(res), code

    except Exception as e:
        res, code = format_response(message=f"An error occurred fetching report details: {str(e)}", status_code=500)
        return jsonify(res), code
