"""
AgriCrop Backend - Moisture Routes
Endpoints for soil moisture predictions, history tracking, and trends.
"""

from flask import Blueprint, request, jsonify
from flask_jwt_extended import jwt_required, get_jwt_identity
from app.services.moisture_service import predict_moisture_levels, get_user_moisture_reports, get_user_moisture_trends
from app.utils.helpers import format_response
from app.utils.validators import validate_moisture_inputs

moisture_bp = Blueprint("moisture", __name__)


@moisture_bp.route("/predict", methods=["POST"])
@jwt_required()
def predict():
    """
    Accept weather and soil parameters, predict soil moisture using Random Forest model,
    save the report to MongoDB, and return the prediction results and recommendations.
    """
    try:
        user_id = get_jwt_identity()
        data = request.get_json() or {}

        # Validate input parameters
        is_valid, err_msg = validate_moisture_inputs(data)
        if not is_valid:
            res, code = format_response(message=err_msg, status_code=400)
            return jsonify(res), code

        # Run moisture prediction service
        result, err = predict_moisture_levels(user_id, data)
        if err:
            res, code = format_response(message=err, status_code=500)
            return jsonify(res), code

        res, code = format_response(result, "Soil moisture analysis completed successfully.", 200)
        return jsonify(res), code

    except Exception as e:
        res, code = format_response(message=f"An error occurred during moisture prediction: {str(e)}", status_code=500)
        return jsonify(res), code


@moisture_bp.route("/reports", methods=["GET"])
@jwt_required()
def reports():
    """Retrieve all soil moisture reports generated by the user."""
    try:
        user_id = get_jwt_identity()
        limit = request.args.get("limit", 20, type=int)

        reports_list, err = get_user_moisture_reports(user_id, limit)
        if err:
            res, code = format_response(message=err, status_code=500)
            return jsonify(res), code

        res, code = format_response(reports_list, "Moisture reports retrieved successfully.", 200)
        return jsonify(res), code

    except Exception as e:
        res, code = format_response(message=f"An error occurred fetching reports: {str(e)}", status_code=500)
        return jsonify(res), code


@moisture_bp.route("/trends", methods=["GET"])
@jwt_required()
def trends():
    """Retrieve moisture trends aggregated by date for analytics charts."""
    try:
        user_id = get_jwt_identity()

        trends_list, err = get_user_moisture_trends(user_id)
        if err:
            res, code = format_response(message=err, status_code=500)
            return jsonify(res), code

        res, code = format_response(trends_list, "Moisture trends retrieved successfully.", 200)
        return jsonify(res), code

    except Exception as e:
        res, code = format_response(message=f"An error occurred fetching trends: {str(e)}", status_code=500)
        return jsonify(res), code
